### ISSUE TITLE
try_credential_hash not decrypting with ntlm hash

### ISSUE THREAD

**Issue by Dionkal** [tijldeneut/DPAPIck3#5]
Hi, I am trying to automate the decryption of Chrome web logins using the dpapick3 library and following the example of the browserdec from dpapilab-ng.

I extract the user hashes using samdump2 and I put the resulting ntlm hash in the try_credential_hash but it's not decrypting. I have also added the CREDHIST using the addCredhistFile but I still don't get any decrypted keys.

I've seen that inside the try_credential hash I still don't get any entries in self.creds[userSID].entries_list
```python
self.creds[userSID].decryptWithHash(pwdhash)
for cred in self.creds[userSID].entries_list:
      mk.decryptWithHash(userSID, cred.pwdhash)
      if cred.ntlm is not None and not mk.decrypted:
           mk.decryptWithHash(userSID, cred.ntlm)
      if mk.decrypted:
           self.creds[userSID].validate()
           break
```

I've also tried running the browserdec.py script with the following arguments:
`python3 browserdec.py -t "paht to local state" --loginfile "path to login data" --mkfile "path to mk file" -a "ntlm user hash"  -s "user SID" -v` and I don't get any results, however, if i replace the hash option with the user password I am able to decrypt the web data.

I know that in the browserdec script it is mentioned that it expects a sha-1 hash of the user password, but in the try_credential_hash function it seems to support ntlm as well. Am I missing something? Shouldn't the decryption be possible using NTLM user hashes as well? If not do you know any other ways that I can obtain sha-1 hashes instead of ntlm from a forensic offine windows copy?

Test files are available upon request.

**Comment by tijldeneut** [comment]
Hi,
Older versions of Windows use NTLM as the hash for encrypting via DPAPI.
However, more recent versions of Windows 10 only rely on SHA-1. 

Getting SHA-1 hashes from a forensic offline copy is difficult or sometimes impossible, but these are your options:
- Brute forcing the NTLM hash using (localized) wordlists with rulesets, it gives you the cleartext password that you can use
- If the machine is domain joined, try getting the domain BCKP PVK from the domain controller
- If the machine was shut down with e.g. updates or certain versions of "quick boot", the autologon credentials might be stored as a SHA1 hash in the registry. This is called TBAL. With a lsa decryptor (e.g. the regdecrypt script in my Diana framework) you could retrieve this from the registry.
- If the machine uses an alternate logon methode (Windows Hello, PIN code, picture logon etc ...) instead of the use typing in the cleartext password, then these might be brute forced/cracked, this too can be done with some of the dpapi-ng scripts in my framework
- ... (there might be other options of course)

Kind Regards
